import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        surface: {
          DEFAULT: "var(--surface)",
          subtle: "var(--surface-subtle)",
          elevated: "var(--surface-elevated)",
          page: "var(--surface-page)",
          base: "var(--surface-base)",
          raised: "var(--surface-raised)",
          inset: "var(--surface-inset)",
          0: "var(--surface-0)",
          1: "var(--surface-1)",
          2: "var(--surface-2)",
          3: "var(--surface-3)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
        },
        border: {
          DEFAULT: "var(--border)",
          strong: "var(--border-strong)",
          subtle: "var(--border-subtle)",
        },
        brand: {
          DEFAULT: "var(--brand)",
          hover: "var(--brand-hover)",
          subtle: "var(--brand-subtle)",
          text: "var(--brand-text)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          hover: "var(--secondary-hover)",
          active: "var(--secondary-active)",
          subtle: "var(--secondary-subtle)",
          text: "var(--secondary-text)",
        },
        mint: {
          DEFAULT: "var(--mint)",
          hover: "var(--mint-strong)",
          active: "var(--mint-strong)",
          subtle: "var(--mint-subtle)",
          strong: "var(--mint-strong)",
        },
        peach: {
          DEFAULT: "var(--peach)",
          hover: "var(--peach-strong)",
          active: "var(--peach-strong)",
          subtle: "var(--peach-subtle)",
          strong: "var(--peach-strong)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          subtle: "var(--accent-subtle)",
          text: "var(--accent-text)",
          light: "var(--accent-hover)",
          dark: "var(--accent)",
          amber: "var(--accent-2)",
        },
        success: {
          DEFAULT: "var(--success)",
          subtle: "var(--success-subtle)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          subtle: "var(--warning-subtle)",
        },
        error: {
          DEFAULT: "var(--error)",
          subtle: "var(--error-subtle)",
        },
        progress: {
          DEFAULT: "var(--progress)",
          hover: "var(--progress-hover)",
          subtle: "var(--progress-subtle)",
          text: "var(--progress-text)",
        },
        info: {
          DEFAULT: "var(--info)",
          subtle: "var(--info-subtle)",
        },
        status: {
          success: "var(--success)",
          warning: "var(--warning)",
          danger: "var(--error)",
          info: "var(--info)",
        },
        primary: {
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
        },
      },
      spacing: {
        "page-x": "var(--space-4)",
        "section-y": "var(--space-8)",
        "control-gap": "var(--space-2)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        display: ["var(--font-plus-jakarta)", "sans-serif"],
      },
      fontWeight: {
        black: "700",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        card: "var(--shadow-card)",
        raised: "var(--shadow-raised)",
        "card-hover": "var(--shadow-raised)",
        modal: "var(--shadow-dialog)",
        dialog: "var(--shadow-dialog)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        pill: "var(--radius-pill)",
        control: "var(--radius-control)",
        card: "var(--radius-card)",
        panel: "var(--radius-panel)",
      },
      animation: {
        "fade-in": "fadeIn 0.14s ease-out",
        "slide-up": "fadeIn 0.14s ease-out",
        "scale-in": "fadeIn 0.14s ease-out",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        scaleIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
      },
    },
  },
  plugins: [],
  safelist: [],
};
export default config;
